### ISSUE TITLE
question

### ISSUE THREAD

**Issue by BAT-FA** [bahrom04/Frame-in-order#1]
What should I add in these two lines `os.chdir("data")
dotenv.load_dotenv()`. Do I add the path to the movie?

**Comment by Bahromoken** [comment]
> What should I add in these two lines `os.chdir("data") dotenv.load_dotenv()`. Do I add the path to the movie?

Also like you I did not understand at first and changed this forked repository.
Link this repo: https://github.com/Bahromoken/Sotqin-kinosidan-lavhalar
I removed ffmpeg part from the code and extracted mp4 video to frames by writing commends in terminal so my code became shorter a bit
If you interested making frame in order bot let me know. I am writing README.md right know for this repo how to make such a bot
